version: "3.7"

services:
  db:
    image: postgres
    container_name: webchat
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    image: web-chat
    depends_on:
      - db
    ports:
      - "4000:4000"